[project]
name = "novel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.0",
    "fastapi>=0.119.0",
    "httpx>=0.28.1",
    "selectolax>=0.4.0",
    "uvicorn>=0.37.0",
]
