name: Shadowgate build

on:
  push:
    paths:
      - "shadowgate/**"
  workflow_dispatch:

jobs:
  Shadowgate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Build and push to Docker Hub
        uses: ./.github/actions/Docker
        with:
          REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_BUILD_NAME: "shadowgate"
          DOCKER_BUILD_PATH: "./shadowgate"
          DOCKER_BUILD_TAG: ${{ github.ref_name == 'main' && 'latest' || 'dev' }}